version = 1

exclude_patterns = [
  '**/examples/**'
]


[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  style_guide = "airbnb"
  module_system = "commonjs"
  environment = ["nodejs"]
  dialect = "typescript"
